Apprendre à utiliser SQLite dans Jupyter

In [94]:
import pandas as pd
import sqlite3

In [95]:
df = pd.read_csv(r'C:\Users\marie\OneDrive\Documents\GitHub\portfolio-data-ia-pharma\projet1-drug-data\data\drugsComTrain_raw.csv')
#aller dans le répertoire du fichier, faire clique droit et selectionner copier le chemin puis venir le coller ici sans oublier d'ajouter un r avant.

In [96]:
df.head(6)
#pour visualiser les 6 premiers lignes

,uniqueID,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9,20-May-12,27
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8,27-Apr-10,192
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5,14-Dec-09,17
3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8,3-Nov-15,10
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9,27-Nov-16,37
5,155963,Cialis,Benign Prostatic Hyperplasia,"""2nd day on 5mg started to work with rock hard...",2,28-Nov-15,43

In [97]:
df.tail(6)
#pour visualiser les 6 dernières

,uniqueID,drugName,condition,review,rating,date,usefulCount
161291,164345,Junel 1.5 / 30,Birth Control,"""This would be my second month on Junel. I&#03...",6,27-May-15,0
161292,191035,Campral,Alcohol Dependence,"""I wrote my first report in Mid-October of 201...",10,31-May-15,125
161293,127085,Metoclopramide,Nausea/Vomiting,"""I was given this in IV before surgey. I immed...",1,1-Nov-11,34
161294,187382,Orencia,Rheumatoid Arthritis,"""Limited improvement after 4 months, developed...",2,15-Mar-14,35
161295,47128,Thyroid desiccated,Underactive Thyroid,"""I&#039;ve been on thyroid medication 49 years...",10,19-Sep-15,79
161296,215220,Lubiprostone,"Constipation, Chronic","""I&#039;ve had chronic constipation all my adu...",9,13-Dec-14,116

In [98]:
df.shape
#pour connaitre le nombre de lignes et de colonne du dataframe

(161297, 7)

In [104]:
connexion = sqlite3.connect(r'C:\Users\marie\OneDrive\Documents\GitHub\portfolio-data-ia-pharma\projet1-drug-data\data\drugsComTrain_raw.db')
#pour établir la connection et pouvoir ouvrir le df
print("Connexion OK")

Connexion OK

In [105]:
df.to_sql('reviews', connexion, if_exists='replace', index=False)
print("Base créée avec succès !")

Base créée avec succès !

In [106]:
resultat = pd.read_sql_query("SELECT drugName, AVG(rating) as note_moyenne FROM reviews GROUP BY drugName ORDER BY note_moyenne DESC LIMIT 10", connexion)
print(resultat)

                          drugName  note_moyenne
0                 Zyrtec-D 12 Hour          10.0
1                           Zymine          10.0
2                         Zutripro          10.0
3                         Zurampic          10.0
4                          Zostrix          10.0
5                       Zinc oxide          10.0
6  Zicam Extreme Congestion Relief          10.0
7                           Zetran          10.0
8                           Zenpep          10.0
9                          Zemaira          10.0

In [107]:
connexion.close()